# Generated by Django 6.1 on 2026-09-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award_skill'),
    ]

    operations = [
    ]
