# Generated by Django 6.1 on 2026-09-20 13:53

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 20, 13, 53, 57, 356333, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
