# Generated by Django 6.1 on 2026-09-20 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_award_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
