# Generated by Django 6.1 on 2026-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_time_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
